(define (insert-sort liste)

  (define (insert element liste)
    (if (null? liste)
        (list element)
        (let ((firstListElement (car liste)) (restListe (cdr liste)))
          (if (< element firstListElement)
              (cons element liste)
              (cons firstListElement (insert element restListe))
          )
        )
    )
  )
  
  (if (null? liste)
    '()
    (insert (car liste) (insert-sort (cdr liste)))
  )
)

; (insert-sort '(2 4 1 6 4))
; (insert-sort '())
; (insert-sort '(3 2 1))
